#the initial samples dir and databases dirs:
db_dir: databases/
q_dir: queries/

processed_db_dir: formatted_db/
results_dir: results/

# additional thresholds if needed here below
#db_search def thresholds 
db_search_gencode: 11
db_search_p: 16
db_search_id: 70
db_search_sub_cover: 50
masking: 0
db_search_outfmt: 6
db_search_b: 6
db_search_max_tar_seqs: 10
